In [1]:
import numpy as np 
from numpy import log,dot,exp,shape
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
import sys

In [13]:
# import sklearn
# dir(sklearn.datasets.make_classification)
print("my name is",sys.argv)

my name is ['C:\\Users\\vishal567795\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py', '-f', 'C:\\Users\\vishal567795\\AppData\\Roaming\\jupyter\\runtime\\kernel-8fee6b2f-d661-4399-a0f2-42caadb19633.json']


In [3]:
X,y = make_classification(n_samples=100,n_features=4)
# print(X)
print(y,len(y),len(X))
type(X)
# help(make_classification())

[1 1 0 1 1 0 0 0 1 1 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1 0 0 0 1 1 0 1 1 0 0 0
 1 0 0 0 1 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 1 1 0 0 1 1 0 0 1 0 1 1 1 0 0 1 0
 1 0 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 1 1 0 0 0] 100 100


numpy.ndarray

In [4]:
from sklearn.model_selection import train_test_split  
X_tr,X_te,y_tr,y_te = train_test_split(X,y,test_size=0.1,train_size=0.9)
# help(train_test_split)
print("X_training:",X_tr,"X_testing",X_te,"y_training",y_tr,"y_te",y_te,sep="\n") 


X_training:
[[ 0.20760756  0.5256946   0.51092317  0.76549181]
 [ 1.10926026  0.46853151 -0.93047654 -1.29310937]
 [-0.72927208  0.02046735  1.12552711  1.60576164]
 [-0.76818504 -0.18681582  0.85967041  1.21213358]
 [-1.17340964 -1.03917371  0.13414234  0.11761319]
 [ 1.28292947  1.68222858  0.70741907  1.12747735]
 [ 0.31685266  1.02398786  1.1264794   1.67818577]
 [-1.06011604 -1.50947891 -0.77132666 -1.20633673]
 [ 1.95422388  0.89973514 -1.52303408 -2.1071967 ]
 [ 0.92315816  1.14581244  0.40789022  0.66254508]
 [-0.91928791 -1.86630007 -1.54058573 -2.32809811]
 [ 1.40709677  1.4978591   0.23286853  0.4380024 ]
 [-1.05956839 -1.37816798 -0.5667685  -0.90546301]
 [-0.77195474 -1.01438199 -0.42904752 -0.68339486]
 [-1.34586079 -1.8161852  -0.8225734  -1.30110335]
 [-3.06410092 -2.02407553  1.42870524  1.89311867]
 [-1.20586561 -1.5011303  -0.53972311 -0.87562072]
 [-1.14185509 -1.20560265 -0.17347878 -0.33265215]
 [-1.00273331 -1.26833307 -0.48020111 -0.77429271]
 [-0.24400786  0.18

In [5]:
# normal form of the training set
help(shape)
def standardize(X_tr):
    for i in range(shape(X_tr)[1]):
        X_tr[:,i] = (X_tr[:,i] - np.mean(X_tr[:,i]))/np.std(X_tr[:,i])
        

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    len
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [6]:
def F1_score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score

In [7]:
class LogidticRegression:
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def fit(self,X,y,alpha=0.001,iter=400):
        weights,X = self.initialize(X)
        def cost(theta):
            z = dot(X,theta)
            cost0 = y.T.dot(log(self.sigmoid(z)))
            cost1 = (1-y).T.dot(log(1-self.sigmoid(z)))
            cost = -((cost1 + cost0))/len(y)
            return cost
        cost_list = np.zeros(iter,)
        for i in range(iter):
            weights = weights - alpha*dot(X.T,self.sigmoid(dot(X,weights))-np.reshape(y,(len(y),1)))
            cost_list[i] = cost(weights)
        self.weights = weights
        return cost_list
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis
    

In [8]:
standardize(X_tr)
standardize(X_te)
obj1 = LogidticRegression()
model= obj1.fit(X_tr,y_tr)
y_pred = obj1.predict(X_te)
y_train = obj1.predict(X_tr)
#Let's see the f1-score for training and testing data
f1_score_tr = F1_score(y_tr,y_train)
f1_score_te = F1_score(y_te,y_pred)
print(f1_score_tr)
print(f1_score_te)

0.9387755102040817
1.0
